# Generated by Django 5.2 on 2025-04-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_logininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('supplier', 'Supplier'), ('contractor', 'Contractor'), ('homeOwner', 'HomeOwner'), ('admin', 'Admin'), ('architecture', 'Architecture')], max_length=20)),
            ],
        ),
    ]
