# Generated by Django 5.2 on 2025-04-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='usertype',
        ),
    ]
