# Generated by Django 5.2 on 2025-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_first_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('contractor', 'Contractor'), ('homeowner', 'homeowner'), ('admin', 'Admin'), ('architecture', 'Architecture')], max_length=20),
        ),
    ]
